---
title: "CM515_finalproject_checklist"
author: "Kelsey Martin"
date: "2024-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Objectives:
Create your own version of the course repo, saving the work you have done.

Use your my-resources repo to make examples and templates easy for you to find in the future.  

Make a portfolio for yourself showcasing the work you have done in the class
 

## my-resources

Add an examples directory and at least one Rmarkdown file from a module you think you'll use in the future. (Use another file if not from an R-based module). 5pts

Make a templates directory and add a starter RMarkdown file. You can use the default that RStudio creates (but I recommend adding some library statements to the first chunk). 5pts

Your version of the CM515 repo

Fork class repo 5pts

Save some completed assignments in your repo. You must do this for at least two modules. 5pts

## Your portfolio

Make a special repository with the same name as your username. This will be the "profile" repository for your account. 5pts

Turn on github pages for your profile. It will build a website for you at https://username.github.io/username/. 5pts

What to put in your portfolio (this is the README.md on your portfolio's repo)
An introduction to yourself.  5pts 

On your portfolio's front page, create a "useful links" link that goes to your my-examples repo.  Use the markdown referenceLinks to an external site. for this.  5pts

On your portfolio's front page, create an "interesting" module link that goes to a module in your fork of the class repo.  5pts
 


 

 

What to turn in
Your github.com link to your profile page.